im:
  mysql:
    host: 127.0.0.1
    port: 3306
    database: zzz-im-server
    username: root
    password: 123456
  redis:
    host: 39.106.183.13
    port: 6379
    password: 123456
  minio:
    endpoint: http://39.106.183.13:9000
    access-key: admin
    secret-key: 12345678
  nacos:
    host: 127.0.0.1
